name: frontend
description: A website to track all your animes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  http_status_code: ^0.0.2
  crypto: ^3.0.1
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2
  google_fonts: ^2.2.0
  styled_widget: ^0.4.0+3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.3
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
